import { Op } from "sequelize";
import models, { sequelize } from "../config/db.js";
import { getValidProduct, getValidUser, insertTransactionItem, isPayloadIdentical, patchTransactionPayload, validatePurchasedAmount } from "../services/transactionService.js";
import _ from "lodash";

// TODO: refactor logic such that backend generates the transaction_timestamp, not given by user payload
// TODO: refactor logic such that created_by is no longer provided manually but automatically generated by whoever is logged in


// TODO: [WARNING!]: REFACTOR AS SOON AS SESSION STORAGE IS POSSIBLE
export const insertTransaction = async (data, t, userId) => {
    data.created_by = userId;

    // Enhancement: support optional status on creation.
    // Defaults to 'completed' to preserve existing sales behavior.
    // Only 'pending' and 'completed' are valid on creation (validated by schema).
    if (!data.status) {
        data.status = 'completed';
    }

    if (data.status === 'completed') {
        data.completed_at = new Date();
    }

    const { transaction_items, ...transactionData } = data  
    const txn = await models.transactions.create(transactionData, { transaction: t })
    const txnJSON = txn.toJSON()

    for (const item of transaction_items) {
        const product = await getValidProduct(item.product_id, t);
        const productJSON = product.toJSON();
        validatePurchasedAmount(item.quantity_bought, product.product_quantity)   
        const txnItem = await insertTransactionItem(productJSON, txnJSON, item, t);

        // Inventory is deducted immediately regardless of status (pending or completed).
        // This reserves the stock for pending transactions and deducts for completed ones.
        await models.products.decrement('product_quantity', {
            by: item.quantity_bought,
            where: {
                product_id: item.product_id,
            },
            transaction: t,
        })
    }

    return txn;
}

export const updateTransaction = async (oldTxn, updatedPayload, userId, t) => {
    // detect difference in payloads
    const isDiff = hasChanges(oldTxn, updatedPayload);
    if (!isDiff) {
        const error = new Error("Invalid edit; no changes detected between new transaction and old transaction.");
        error.status = 400;
        throw error;
    }

    // rollback items
    for (const item of oldTxn.transaction_items) {
        const product = await getValidProduct(item.product_id, t);
        await product.increment('product_quantity', {
            by: item.quantity_bought,
            transaction: t,
        })
    }

    const syncedTimestamp = new Date();

    const s = await models.transactions.findByPk(oldTxn.transaction_id);
    await s.update({ voided_at: syncedTimestamp }, { transaction: t });

    for (const item of updatedPayload.transaction_items) {
        const product = await models.products.findByPk(item.product_id, { transaction: t });
        
        if (product.product_quantity < item.quantity_bought) {
            const error = new Error(`Insufficient stocks for ${product.product_name}. Only ${product.product_quantity} are available`);
            error.status = 400;
            throw error;
        }
    }
    
    const newTxn = await insertTransaction({...updatedPayload, created_at: syncedTimestamp }, t, userId);

    return newTxn;
}

export const getTransactionByMonthAndYear = async (month, year, status = null) => {
    const startDate = new Date(year, month - 1, 1);
    const endDate = new Date(year, month, 1);

    const allowedStatuses = ['pending', 'completed', 'cancelled'];

    // Build where clause. Always exclude voided (edited) records.
    const where = {
        created_at: {
            [Op.gte]: startDate,
            [Op.lt]: endDate,
        },
        voided_at: null,
    };

    // Enhancement: if a valid status filter is provided, apply it.
    // If status is 'all' or not provided, return all non-voided transactions.
    if (status && status !== 'all' && allowedStatuses.includes(status)) {
        where.status = status;
    }

    const transactions = await models.transactions.findAll({
        where,
        include: {
            model: models.transaction_items,
            as: "transaction_items",
        },
        order: [['created_at', 'DESC']]
    })

    return transactions;
}

// Enhancement: Update the status of a transaction following strict lifecycle rules.
export const updateTransactionStatus = async (transactionId, newStatus, t) => {
    const allowedNewStatuses = ['completed', 'cancelled'];

    if (!allowedNewStatuses.includes(newStatus)) {
        const error = new Error('Invalid status. Only "completed" or "cancelled" are allowed.');
        error.status = 400;
        throw error;
    }

    const txn = await models.transactions.findOne({
        where: { transaction_id: transactionId, voided_at: null },
        include: { model: models.transaction_items, as: 'transaction_items' },
        transaction: t,
    });

    if (!txn) {
        const error = new Error('Transaction not found.');
        error.status = 404;
        throw error;
    }

    const currentStatus = txn.status;

    // Enforce strict lifecycle rules:
    if (currentStatus === 'completed') {
        const error = new Error('Completed transactions cannot be changed in this version.');
        error.status = 400;
        throw error;
    }

    if (currentStatus === 'cancelled') {
        const error = new Error('Cancelled transactions cannot be changed.');
        error.status = 400;
        throw error;
    }

    if (currentStatus === newStatus) {
        const error = new Error(`Transaction is already ${currentStatus}.`);
        error.status = 400;
        throw error;
    }

    // Transition: pending → cancelled
    // Restore the reserved inventory for each item.
    if (currentStatus === 'pending' && newStatus === 'cancelled') {
        for (const item of txn.transaction_items) {
            await models.products.increment('product_quantity', {
                by: item.quantity_bought,
                where: { product_id: item.product_id },
                transaction: t,
            });
        }
    }

    // Transition: pending → completed
    // No inventory change — stock was already reserved on creation.
    const updateData = { status: newStatus };
    if (newStatus === 'completed') {
        updateData.completed_at = new Date();
    }

    await txn.update(updateData, { transaction: t });

    // Reload to ensure completed_at and all fields reflect the persisted DB state.
    await txn.reload({
        include: { model: models.transaction_items, as: 'transaction_items' },
        transaction: t,
    });

    return txn;
}

export const getAllTransactionsByMonthAndYear = async (month, year) => {
    const startDate = new Date(year, month - 1, 1);
    const endDate = new Date(year, month, 1);

    const transactions = await models.transactions.findAll({
        where: {
            created_at: {
                [Op.gte]: startDate,
                [Op.lt]: endDate,
            },
        },
        include: [
            {
                model: models.transaction_items,
                as: "transaction_items",
            },
            {
                model: models.users,
                as: "created_by_user",
                attributes: ['username']
            }
        ],
        order: [['created_at', 'DESC']]
    })

    return transactions;
}

const hasChanges = (transaction, formData) => {
    const detailsChanged =
        (transaction.payment_type !== formData.payment_type) ||
        (transaction.payment_refstr !== formData.payment_refstr);
    if (detailsChanged) { 
        return true;
    }
    const oldProducts = _.sortBy(transaction.transaction_items, 'product_id')
        .map(item => _.pick(item, ['product_id', 'quantity_bought']));
    const newProducts = _.sortBy(formData.transaction_items, 'product_id')
        .map(item => _.pick(item, ['product_id', 'quantity_bought']));

    return !_.isEqual(oldProducts, newProducts);
};