import { Op } from "sequelize";
import { registerConsoleShortcuts } from "vitest/node";
import models, { sequelize } from "../config/db.js";
import { where } from "sequelize";
import { getValidProduct, getValidUser, insertTransactionItem, isPayloadIdentical, patchTransactionPayload, validatePurchasedAmount } from "../services/transactionService.js";
import { createActivityLog } from "../services/activityLogService.js";

// TODO: refactor logic such that backend generates the transaction_timestamp, not given by user payload
// TODO: refactor logic such that created_by is no longer provided manually but automatically generated by whoever is logged in


// TODO: [WARNING!]: REFACTOR AS SOON AS SESSION STORAGE IS POSSIBLE
export const insertTransaction = async (data, t, userId) => {
    data.transaction_timestamp = Date.now();
    data.created_by = userId;

    const { transaction_items, ...transactionData } = data  
    const txn = await models.transactions.create(transactionData, { transaction: t })
    const txnJSON = txn.toJSON()

    for (const item of transaction_items) {
        const product = await getValidProduct(item.product_id, t);
        const productJSON = product.toJSON();
        validatePurchasedAmount(item.quantity_bought, product.product_quantity)   
        const txnItem = await insertTransactionItem(productJSON, txnJSON, item, t);

        await models.products.decrement('product_quantity', {
            by: item.quantity_bought,
            where: {
                product_id: item.product_id,
            },
            transaction: t,
        })
    }

    // Log the transaction creation
    await createActivityLog({
        action: "TRANSACTION_CREATED",
        module: "transactions",
        description: `Transaction #${txnJSON.transaction_id} created (${transactionData.payment_type})`,
        reference_id: txnJSON.transaction_id,
        new_value: txnJSON,
        performed_by: userId,
    }, t);

    return txn;
}

export const updateTransaction = async (oldTxn, updatedPayload, userId, t) => {
    updatedPayload.transaction_timestamp = Date.now();
    
    // rollback items
    for (const item of oldTxn.transaction_items) {
        const product = await getValidProduct(item.product_id, t);
        await product.increment('product_quantity', {
            by: item.quantity_bought,
            transaction: t,
        })
    }

    const s = await models.transactions.findByPk(oldTxn.transaction_id);
    await s.update({ voided_at: Date.now() }, { transaction: t });
    
    const newTxn = await insertTransaction(updatedPayload, t, userId);
    // TODO: Modify above line once a user_id fetching function is created

    // Log the transaction update (void old + create new is already logged by insertTransaction)
    await createActivityLog({
        action: "TRANSACTION_UPDATED",
        module: "transactions",
        description: `Transaction #${oldTxn.transaction_id} voided and replaced by #${newTxn.toJSON().transaction_id}`,
        reference_id: oldTxn.transaction_id,
        previous_value: oldTxn,
        new_value: newTxn.toJSON(),
        performed_by: userId,
    }, t);

    return newTxn;
}

export const getTransactionByMonthAndYear = async (month, year) => {
    const startDate = new Date(year, month - 1, 1);
    const endDate = new Date(year, month, 1);

    const transactions = await models.transactions.findAll({
        where: {
            transaction_timestamp: {
                [Op.gte]: startDate,
                [Op.lt]: endDate,
            }
        },
        include: {
            model: models.transaction_items,
            as: "transaction_items",
        },
        order: [['transaction_timestamp', 'DESC']]
    })

    return transactions;
}